name: Checkout-example

on: [push]

jobs:
  checkout-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: actions/checkout@v4

      - name: List files
        run: ls -a