name: matrix-yaml

on: [push]

jobs:
  matrix-job:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Print OS 
        run: echo"Running on ${{ matrix.os }}"